version: '3'

services:
    python:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./BookShop:/BookShop
        ports:
            - "8000:8000"