version: '3.11'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./BookShop:/BookShop
    ports:
      - "8000:8000"
    command: sh -c "sleep 10 && python manage.py migrate"
  db:
    image: postgres
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=74385201
        - POSTGRES_DB=BookShop