# Generated by Django 4.1.6 on 2023-07-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_hyperlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_github',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_linkedin',
            field=models.URLField(default=''),
        ),
    ]
