# Generated by Django 4.1.6 on 2023-08-03 09:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('genre', models.CharField(choices=[('Fantasy', 'Fantasy'), ('Adventure', 'Adventure'), ('Love', 'Love'), ('Historic', 'Historic'), ('Detective', 'Detective')], max_length=255, null=True)),
                ('price', models.IntegerField(default=0, max_length=100)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('date_released', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WisthlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('book_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witems', to='Books.book')),
                ('wisthlist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wisthlistitems', to='Books.wishlist')),
            ],
        ),
    ]
