# Generated by Django 4.2.4 on 2023-08-29 09:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(blank=True, max_length=255)),
                ('book_author', models.CharField(blank=True, max_length=255)),
                ('book_year', models.CharField(blank=True, choices=[('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018')], max_length=4)),
                ('desc', models.TextField(blank=True)),
                ('genre', models.CharField(blank=True, choices=[('Fantasy', 'Fantasy'), ('Adventure', 'Adventure'), ('Love', 'Love'), ('Historic', 'Historic'), ('Detective', 'Detective')], max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, default=0, max_length=100)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=255)),
                ('time_accepted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('date_released', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WisthlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('book_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witems', to='Books.book')),
                ('wisthlist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wisthlistitems', to='Books.wishlist')),
            ],
        ),
    ]
