# Generated by Django 4.2.4 on 2023-08-29 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useraccount', '0001_initial'),
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.simpleuser'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.simpleuser'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book'),
        ),
        migrations.AddField(
            model_name='contact',
            name='ordered_books',
            field=models.ManyToManyField(to='Books.cartitem'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.simpleuser'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='book_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Books.book'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='Books.cart'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.simpleuser'),
        ),
    ]
