# Generated by Django 4.1.6 on 2023-06-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
